version: '3.8'

services:
  # --- Blue 인스턴스 ---
  backend-blue:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:blue
    container_name: backend-blue
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_ENDPOINT: ${RDS_ENDPOINT}
      RDS_PORT: ${RDS_PORT}
      RDS_DATABASE: ${RDS_DATABASE}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      ELASTICACHE_ENDPOINT: ${ELASTICACHE_ENDPOINT}
      ELASTICACHE_PORT: ${ELASTICACHE_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/test/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # --- Green 인스턴스 ---
  backend-green:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:green
    container_name: backend-green
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_ENDPOINT: ${RDS_ENDPOINT}
      RDS_PORT: ${RDS_PORT}
      RDS_DATABASE: ${RDS_DATABASE}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      ELASTICACHE_ENDPOINT: ${ELASTICACHE_ENDPOINT}
      ELASTICACHE_PORT: ${ELASTICACHE_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/test/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # --- Nginx 리버스 프록시 ---
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/app/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/app/service-env.inc:/etc/nginx/conf.d/service-env.inc:ro
    depends_on:
      backend-blue:
        condition: service_healthy
      backend-green:
        condition: service_healthy
    restart: always

networks:
  default:
    driver: bridge
