version: '3.8'

services:
  backend-blue:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: backend-blue
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_ENDPOINT:         ${RDS_ENDPOINT}
      RDS_PORT:             ${RDS_PORT}
      RDS_DATABASE:         ${RDS_DATABASE}
      RDS_USERNAME:         ${RDS_USERNAME}
      RDS_PASSWORD:         ${RDS_PASSWORD}
      ELASTICACHE_ENDPOINT: ${ELASTICACHE_ENDPOINT}
      ELASTICACHE_PORT:     ${ELASTICACHE_PORT}
      JWT_SECRET_KEY:       ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME:  ${JWT_EXPIRATION_TIME}

      ECR_REGISTRY:        ${ECR_REGISTRY}
      ECR_REPOSITORY:      ${ECR_REPOSITORY}
      IMAGE_TAG:           ${IMAGE_TAG}

    restart: always

  backend-green:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: backend-green
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_ENDPOINT:         ${RDS_ENDPOINT}
      RDS_PORT:             ${RDS_PORT}
      RDS_DATABASE:         ${RDS_DATABASE}
      RDS_USERNAME:         ${RDS_USERNAME}
      RDS_PASSWORD:         ${RDS_PASSWORD}
      ELASTICACHE_ENDPOINT: ${ELASTICACHE_ENDPOINT}
      ELASTICACHE_PORT:     ${ELASTICACHE_PORT}
      JWT_SECRET_KEY:       ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME:  ${JWT_EXPIRATION_TIME}

      ECR_REGISTRY:        ${ECR_REGISTRY}
      ECR_REPOSITORY:      ${ECR_REPOSITORY}
      IMAGE_TAG:           ${IMAGE_TAG}

    restart: always

  nginx:
    image: public.ecr.aws/docker/library/nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/app/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/app/service-env.inc:/etc/nginx/conf.d/service-env.inc:ro
    restart: always