### Auth Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "testpassword"
}

### 로그아웃 (토큰 포함)
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc0NTc0MDE1NywiZXhwIjoxNzQ1Nzc2MTU3fQ.VZdn7eKgWfqG2MYo7LRc4GcvLrZLGFtyq3ufGgNKTlg
