server:
  port: 8080

spring:

  application:
    name: focussu-backend

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      port: ${ELASTICACHE_PORT}
      host: ${ELASTICACHE_ENDPOINT}

springdoc:
  default-produces-media-type: application/json
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    path: /docs

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}