name: CD - Deploy to EC2 (Blue-Green)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:            ${{ secrets.AWS_REGION }}
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution:  'temurin'

      - name: Build Spring Boot JAR (without tests)
        run: ./gradlew bootJar -x test
        working-directory: ./backend

      - name: Determine Image Tag (SHA7)
        id: tag
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT :contentReference[oaicite:6]{index=6}

      - name: Build & Push Docker Image
        env:
          ECR_REGISTRY:   ${{ steps.login.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG:      ${{ steps.tag.outputs.tag }}
        run: |
          docker build \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            ./backend --build-arg JAR_FILE=build/libs/*.jar
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" :contentReference[oaicite:7]{index=7}

  deploy-blue-green:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:            ${{ secrets.AWS_REGION }}
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: SSH & Deploy via script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:        ${{ secrets.EC2_HOST }}
          username:    ubuntu
          key:         ${{ secrets.EC2_SSH_KEY }}
          port:        22
          script_stop: true
          envs: |
            AWS_REGION=${{ secrets.AWS_REGION }}
            ECR_REGISTRY=${{ steps.login.outputs.registry }}
            ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
            IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
            RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }}
            RDS_PORT=${{ secrets.RDS_PORT }}
            RDS_DATABASE=${{ secrets.RDS_DATABASE }}
            RDS_USERNAME=${{ secrets.RDS_USERNAME }}
            RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}
            ELASTICACHE_ENDPOINT=${{ secrets.ELASTICACHE_ENDPOINT }}
            ELASTICACHE_PORT=${{ secrets.ELASTICACHE_PORT }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}
          script: |
            # 이 한 줄로 remote에서 deploy.sh 실행
            ./app/scripts/deploy.sh
