name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-only:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build without tests
        run: ./gradlew build -x test --no-daemon
